### ISSUE TITLE
cant open kali

### ISSUE THREAD

**Issue by ismailkhalouti** [MasterDevX/Termux-Kali#3] opened 2019-10-27 14:34 UTC
t
![Screenshot_20191027-152649](https://user-images.githubusercontent.com/37406648/67636240-f5a9ad00-f8ce-11e9-9017-90f42339bf5a.jpg)

screenshoot

**Comment by MasterDevX** [comment] 2019-11-01 18:24
Duplicate of https://github.com/MasterDevX/Termux-Kali/issues/1

**Closed by MasterDevX** 2019-11-01 18:24 UTC
